name: pim_core
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: 4.6.5

  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  cloud_functions: ^4.1.1
  firebase_storage: ^11.1.1
  firebase_messaging: ^14.4.1
  get_storage: ^2.1.1
  getwidget: ^3.1.1


dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

